const CORPUS = new Map([
  ["0.", {sno:"0.",title:"Introduction",pagenos:"1"}],
  ["1.", {sno:"1.",title:"Nutrients and Their Functions",pagenos:"2-23"}],
  ["2.", {sno:"2.",title:"Non-Nutrient Components of Foods",pagenos:"24-26"}],
  ["3.", {sno:"3.",title:"Foods and Their Nutrient Content",pagenos:"27-31"}],
  ["4.", {sno:"4.",title:"Effect of Processing on Nutritive Value of Foods",pagenos:"32-33"}],
  ["5.", {sno:"5.",title:"Nutrient Requirement and Recommended Dietary Allowances",pagenos:"34"}],
  ["6.", {sno:"6.",title:"Habitual Diets in India and Their Adequacy",pagenos:"35-36"}],
  ["7.", {sno:"7.",title:"Nutritional Deficiencies, Their Prevention and Control",pagenos:"37-39"}],
  ["8.", {sno:"8.",title:"Dietary Guidelines",pagenos:"40-41"}],
  ["N.", {sno:"N.",title:"Notes on Food Composition Tables",pagenos:"42-43"}],
  ["T.", {sno:"T.",title:"Food Composition Tables",pagenos:"45"}],
  ["T1.", {sno:"T1.",title:"Proximate Principles : Common Foods",pagenos:"47-58"}],
  ["T2.", {sno:"T2.",title:"Vitamin Content : Common Foods",pagenos:"59-67"}],
  ["T3.", {sno:"T3.",title:"Mineral and Trace Elements : Common Foods",pagenos:"68-73"}],
  ["T4.", {sno:"T4.",title:"Proximate Principles : Less Familiar Foods",pagenos:"74-77"}],
  ["T5.", {sno:"T5.",title:"Vitamin Content : Less Familiar Foods",pagenos:"78-79"}],
  ["T6.", {sno:"T6.",title:"Mineral and Trace Elements : Less Familiar Foods",pagenos:"80"}],
  ["T7.", {sno:"T7.",title:"Essential Amino Acids : Common Foods",pagenos:"81-84"}],
  ["T8.", {sno:"T8.",title:"Essential Amino Acids : Less Familiar Foods",pagenos:"85"}],
  ["T9.", {sno:"T9.",title:"Fatty Acid Composition of Edible Oils and Fats",pagenos:"86"}],
  ["T10.", {sno:"T10.",title:"Fat and Fatty Acid Composition of Common Foods",pagenos:"87"}],
  ["T11.", {sno:"T11.",title:"Vitamin B12 Content",pagenos:"88"}],
  ["T12.", {sno:"T12.",title:"Oxalic Acid and Phytin Phosphorus in Foods",pagenos:"89-92"}],
  ["T13.", {sno:"T13.",title:"Total, Insoluble and Soluble Dietary Fibre in Foods",pagenos:"93-95"}],
  ["A1.", {sno:"A1.",title:"APPENDIX - I: Recommended Dietary Allowances for Indians",pagenos:"96-98"}],
  ["A2.", {sno:"A2.",title:"APPENDIX - II: Names of Food Stuffs in Indian Languages",pagenos:"99-122"}],
  ["I.", {sno:"I.",title:"INDEX OF FOODSTUFFS",pagenos:"123-161"}],
]);
module.exports = CORPUS;
