var CORPUS = new Map([
  ["code", {code:"code",name:"Food Code",tags:"id tag legend"}],
  ["name", {code:"name",name:"Food Name",tags:"title label"}],
  ["scie", {code:"scie",name:"Scientific Name",tags:"binomial genus botanical"}],
  ["grup", {code:"grup",name:"Food Group",tags:"category class classification grouping type sort kind"}],
  ["tags", {code:"tags",name:"Tags",tags:""}],
  ["water", {code:"water",name:"Moisture",tags:"total liquid steam vapour proximate"}],
  ["protcnt", {code:"protcnt",name:"Protein",tags:"total essential macronutrient proximate"}],
  ["fatce", {code:"fatce",name:"Fat",tags:"total triglyceride lipid blubber essential macronutrient"}],
  ["ash", {code:"ash",name:"Minerals",tags:"total metal oxide mineral inorganic element residue proximate"}],
  ["fibtg", {code:"fibtg",name:"Crude Fiber",tags:"dietary fibre roughage bulk indigestible"}],
  ["choavldf", {code:"choavldf",name:"Carbohydrates",tags:"total cho saccharide ose glucide hydrate carbon macronutrient proximate"}],
  ["enerc", {code:"enerc",name:"Energy",tags:"total atp calorie metabolism essential proximate kj kilojoule kilo joule"}],
  ["ca", {code:"ca",name:"Calcium (Ca)",tags:"quantity alkaline earth metal mineral chemical element"}],
  ["p", {code:"p",name:"Phophorus (P)",tags:"quantity nonmetal mineral chemical element"}],
  ["fe", {code:"fe",name:"Iron (Fe)",tags:"trace transition metal mineral chemical element"}],
  ["cartoid", {code:"cartoid",name:"Carotene",tags:"total carotene xanthophyll carotenoid tetraterpenoid terpenoid isoprenoid phytochemical orange yellow pigment"}],
  ["thia", {code:"thia",name:"Thiamine (B1)",tags:"thiamin aneurine vitamin b1 b 1 water soluble essential"}],
  ["ribf", {code:"ribf",name:"Riboflavin (B2)",tags:"vactochrome lactoflavin vitamin b2 b 2 water soluble g essential"}],
  ["nia", {code:"nia",name:"Niacin (B3)",tags:"nicotinic acid nicotinamide bionic vitamin b3 b 3 pp water soluble essential white translucent crystalline crystal"}],
  ["vitb6c", {code:"vitb6c",name:"Total B6",tags:"pn p5p pl plp pm pmp pa pyridoxine pyridoxal pyridoxamine pyridoxic acid pyritinol vitamer vitamin b6 b 6 water soluble essential"}],
  ["folfre", {code:"folfre",name:"Folic Acid (B9) (free)",tags:"folate pteroyl glutamic acid glutamate folic folacin vitamin b9 b9 b 9 bc m water soluble essential"}],
  ["folsum", {code:"folsum",name:"Folic Acid (B9) (Total)",tags:"folate pteroyl glutamic acid glutamate folic folacin vitamin b9 b9 b 9 bc m water soluble essential"}],
  ["vitc", {code:"vitc",name:"Vitamin C",tags:"ascorbic acid total ascorbate water soluble essential"}],
]);
module.exports = CORPUS;
